---
version: '2'

networks:
  tig:

services:
  influxdb:
    image: influxdb:1.7.2
    container_name: influxdb
    expose:
      - 8086
      - 8083
    networks:
      - tig

  telegraf-openconfig:
    image: telegraf:1.9.1
    container_name: telegraf-openconfig
    volumes:
      - $PWD/configs/telegraf-openconfig.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - "influxdb"
    networks:
      - tig

  telegraf-snmp:
    image: ksator/telegraf_with_snmp_mib
    container_name: telegraf-snmp
    volumes:
      - $PWD/configs/telegraf-snmp.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - "influxdb"
    networks:
      - tig

  grafana:
    image: grafana/grafana:5.4.2
    container_name: grafana
    ports:
      - "9081:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=jcluser
      - GF_SECURITY_ADMIN_PASSWORD=Juniper!1
    volumes:
      - $PWD/configs/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
      - $PWD/configs/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml:ro
      - $PWD/dashboards:/var/tmp/dashboards
    depends_on:
      - "telegraf-openconfig"
      - "telegraf-snmp"
    networks:
      - tig